name: Push to S3 bucket

on:
  push:
    tags:
      - "v[0-9]+"
      - "v[0-9]+-*"
      - "v[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+-*"
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"
    branches:
      - "**"

jobs:
  s3:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Get image tag
        run: echo IMAGE_TAG=$(if [[ "${GITHUB_REF##refs/tags/}" =~ ^v ]]; then echo ${GITHUB_REF##refs/tags/}; else echo "${GITHUB_REF##refs/heads/}"; fi) >> "$GITHUB_ENV"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Node files
        run: |
          npm install mini-css-extract-plugin 
          npm install css-loader 
          npm install crypto-browserify
          npm install stream-browserify
          npm install browserify-zlib
          export APP_PUBLIC_PATH=/static-apps/resource-catalogue/$IMAGE_TAG
          npm run build

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3 bucket
        run: |
          echo ls
          aws s3 cp dist s3://eodhp-static-web-artefacts/static-apps/resource-catalogue/$IMAGE_TAG --recursive
